const STORAGE_KEY='alawss_listings_v1';
const DEFAULT_LISTINGS=[
 {id:'1053',type:'استراحة',city:'عنيزة',district:'حي الفرعية',deal:'إيجار',price:5450,period:'كل 6 أشهر',features:['عداد كهرباء مستقل','كراج'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85'},
 {id:'1061',type:'شقة علوية',city:'عنيزة',district:'حي شيخة',deal:'إيجار',price:10450,period:'كل 6 أشهر',features:['مدخل مستقل','مطبخ ومكيفات راكبة'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85'},
 {id:'1023',type:'استراحة',city:'عنيزة',district:'حي الزاهر',deal:'إيجار',price:7750,period:'كل 6 أشهر',features:['كراج','عداد كهرباء مستقل'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85'},
 {id:'1056',type:'شقة علوية',city:'عنيزة',district:'حي البديعة',deal:'إيجار',price:9950,period:'كل 6 أشهر',features:['مدخل مستقل','مكيفات راكبة'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85'},
 {id:'1042',type:'فيلا',city:'عنيزة',district:'حي اليمامة',deal:'إيجار',price:30450,period:'كل 6 أشهر',features:['موقع مميز','المطبخ والمكيفات راكبة'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1000&q=85'},
 {id:'1034',type:'مكتب تجاري',city:'عنيزة',district:'طريق عمر بن الخطاب',deal:'إيجار',price:6450,period:'كل 6 أشهر',features:['عداد كهرباء مستقل','شارع تجاري مميز'],status:'متاح',featured:true,img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85'}
];
function read(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(v))return v}catch(e){} localStorage.setItem(STORAGE_KEY,JSON.stringify(DEFAULT_LISTINGS));return [...DEFAULT_LISTINGS]}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(listings))}
let listings=read();
let uploadedData='';
const rows=document.getElementById('propertyRows'),stats=document.getElementById('stats'),drawer=document.getElementById('propertyDrawer'),form=document.getElementById('propertyForm'),preview=document.getElementById('imagePreview'),search=document.getElementById('adminSearch'),statusFilter=document.getElementById('statusFilter');
const money=n=>new Intl.NumberFormat('ar-SA').format(Number(n)||0);
function getNextListingId(){
  const nums=listings.map(x=>Number.parseInt(String(x.id).replace(/\D/g,''),10)).filter(Number.isFinite);
  return String((nums.length?Math.max(...nums):0)+1);
}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function renderStats(){const total=listings.length,available=listings.filter(x=>x.status==='متاح').length,rented=listings.filter(x=>x.status==='مؤجر').length,featured=listings.filter(x=>x.featured).length;stats.innerHTML=`<article class="stat accent"><small>إجمالي العقارات</small><strong>${total}</strong></article><article class="stat"><small>متاح</small><strong>${available}</strong></article><article class="stat"><small>مؤجر</small><strong>${rented}</strong></article><article class="stat"><small>مميز في الرئيسية</small><strong>${featured}</strong></article>`}
function statusClass(s){return s==='متاح'?'available':s==='مؤجر'?'rented':'off'}
function filtered(){const q=search.value.trim().toLowerCase(),s=statusFilter.value;return listings.filter(x=>(s==='all'||x.status===s)&&(!q||[x.id,x.type,x.city,x.district].join(' ').toLowerCase().includes(q)))}
function renderRows(){const data=filtered();document.getElementById('propertyCount').textContent=`${data.length} عقار`;document.getElementById('adminEmpty').hidden=!!data.length;rows.innerHTML=data.map(x=>`<tr><td><div class="property-cell"><img src="${x.img}" alt=""><span><strong>${x.type}</strong><small>${x.deal}</small></span></div></td><td>#${x.id}</td><td>${x.district}<br><small>${x.city}</small></td><td><strong>${money(x.price)} ر.س</strong><br><small>${x.period||''}</small></td><td><span class="status ${statusClass(x.status)}">${x.status}</span></td><td><span class="feature-dot ${x.featured?'on':''}" title="${x.featured?'مميز':'غير مميز'}"></span></td><td><div class="row-actions"><button data-edit="${x.id}">تعديل</button><button data-toggle="${x.id}">${x.status==='غير متاح'?'تفعيل':'إيقاف'}</button><button class="danger" data-delete="${x.id}">حذف</button></div></td></tr>`).join('');bindActions()}
function render(){renderStats();renderRows()}
function openDrawer(item=null){form.reset();uploadedData='';form.editingId.value=item?item.id:'';document.getElementById('drawerTitle').textContent=item?'تعديل العقار':'إضافة عقار';if(item){for(const [k,v] of Object.entries(item)){if(k==='features'||k==='featured'||k==='img'||k==='id')continue;if(form.elements[k])form.elements[k].value=v??''}form.elements.id.value=item.id;form.elements.features.value=(item.features||[]).join('\n');form.elements.img.value=item.img||'';form.elements.featured.checked=!!item.featured;setPreview(item.img)}else{form.elements.id.value=getNextListingId();form.elements.status.value='متاح';form.elements.featured.checked=true;setPreview('')}drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function setPreview(src){preview.style.backgroundImage=src?`url("${src}")`:'';preview.querySelector('span')?.remove();if(!src)preview.innerHTML='<span>معاينة الصورة</span>';else preview.innerHTML=''}
document.getElementById('addPropertyBtn').onclick=()=>openDrawer();document.querySelectorAll('[data-close-drawer]').forEach(b=>b.onclick=closeDrawer);search.oninput=renderRows;statusFilter.onchange=renderRows;
document.getElementById('imageUpload').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>900000){toast('يفضل صورة أقل من 900KB في النسخة التجريبية');return}const r=new FileReader();r.onload=()=>{uploadedData=r.result;setPreview(uploadedData)};r.readAsDataURL(file)});form.elements.img.addEventListener('input',e=>{if(!uploadedData)setPreview(e.target.value.trim())});
form.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form),editing=fd.get('editingId'),id=editing?String(editing):getNextListingId();const old=listings.find(x=>String(x.id)===String(editing));const item={id,type:fd.get('type'),city:fd.get('city'),district:fd.get('district').trim(),deal:fd.get('deal'),price:Number(fd.get('price')),period:fd.get('period').trim(),features:fd.get('features').split('\n').map(s=>s.trim()).filter(Boolean),status:fd.get('status'),featured:fd.get('featured')==='on',img:uploadedData||fd.get('img').trim()||old?.img||'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1000&q=80'};if(editing){listings=listings.map(x=>String(x.id)===String(editing)?item:x);toast('تم تحديث العقار')}else{listings.unshift(item);toast('تمت إضافة العقار')}save();render();closeDrawer()});
function bindActions(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openDrawer(listings.find(x=>String(x.id)===b.dataset.edit)));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const x=listings.find(v=>String(v.id)===b.dataset.toggle);if(!x)return;x.status=x.status==='غير متاح'?'متاح':'غير متاح';save();render();toast(x.status==='متاح'?'تم تفعيل العقار':'تم إيقاف العقار')});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const x=listings.find(v=>String(v.id)===b.dataset.delete);if(!x)return;if(confirm(`حذف الإعلان رقم ${x.id}؟`)){listings=listings.filter(v=>String(v.id)!==String(x.id));save();render();toast('تم حذف العقار')}})}
render();
